(function(){'use strict';
const channels=[
[7001,'Матч ТВ','matchtv.html','Match TV'],[7002,'Матч Премьер','match-premier.html','Match Premier'],[7003,'Матч Арена','match-arena.html','Match Arena'],[7004,'Матч Футбол 1','match-football-1.html','Match Football 1'],[7005,'Матч Футбол 2','match-football-2.html','Match Football 2'],[7006,'Матч Футбол 3','match-football-3.html','Match Football 3'],[7007,'Сетанта Спорт 1','setanta-1.html','Setanta Sports 1'],[7008,'Сетанта Спорт 2','setanta-2.html','Setanta Sports 2'],[7009,'Сетанта Украина','setanta-ua.html','Setanta Ukraine'],[7010,'Сетанта Спорт Плюс','setanta-plus.html','Setanta Sports Plus'],[7011,'Евроспорт 1','eurosport-1.html','Eurosport 1'],[7012,'Евроспорт 2','eurosport-2.html','Eurosport 2'],[7013,'Окко Спорт','okko-sport.html','Okko Sport'],[7014,'Окко Футбол','okko-football.html','Okko Football'],[7015,'Конный Мир','konnyj-mir.html','Horse World'],[7016,'Viju Sport','viju-sport.html','Viju Sport'],[7017,'Qazsport','qazsport.html','Qazsport'],[7018,'Волейбол','voleybol.html','Volleyball'],[7019,'Футбол','footballru.html','Football RU'],[7020,'КХЛ','khl.html','KHL'],[7021,'Astrakhan Sport','astrakhan.html','Astrakhan Sport'],[7022,'Удар','udar.html','Udar'],[7023,'Бокс','bokstv.html','Boxing'],[7024,'Боец','boyets.html','Boyets'],[7025,'Fast Sports','fast-sports.html','Fast Sports'],[7026,'NBA','nba.html','NBA'],[7027,'Беларусь 5','belarus5.html','Belarus 5'],[7028,'Беларусь 5 Интернет','belarus5-internet.html','Belarus 5 Internet'],[7029,'UPL 1','upl1hd.html','UPL 1'],[7030,'UPL 2','upl2hd.html','UPL 2']
];
const root='./';
const grid=document.getElementById('channels'), playerSection=document.getElementById('player-section'), player=document.getElementById('player'), title=document.getElementById('player-title');
const lang=(new URLSearchParams(location.search).get('lang')||localStorage.getItem('matchpro-app-lang')||'ru')==='en'?'en':'ru';
let currentLang=lang;
const logos=['Match_TV_logo.png','Match_Premier_logo.png','Match_Arena_logo.png','Match_Footbal_1_logo.png','Match_Footbal_2_logo.png','Match_Footbal_3_logo.png','Setanta_Sport_1_logo.png','Setanta_Sport_2_logo.png','Setanta_Sport_UA_logo.png','Setanta_Sport_PLUS_logo.png','EuroSport_1_logo.png','EuroSport_2_logo.png','Okko_Sport_logo.png','Okko_Football_logo.png','Konnyj_Mir_logo.png','Viju_Sport_logo.png','QazSport_logo.png','Voleybol_logo.png','Football_RU_logo.png','Khl_logo.png','Khl_Prime_logo.png','Udar_logo.png','Boks_logo.png','Boyets_logo.png','Fast_Sports_logo.png','NBA_logo.png','Belarus_5_logo.png','Belarus_5_internet_logo.png','Upl_1_logo.png','Upl_2_logo.png'];
function render(){grid.innerHTML='';channels.forEach(function(c,i){const a=document.createElement('a');a.className='channel';a.href='?id='+c[0]+'&lang='+currentLang;a.dataset.id=c[0];const img=document.createElement('img');img.src=root+'media/logo/'+logos[i];img.alt=currentLang==='en'?c[3]:c[1];img.loading='lazy';img.decoding='async';a.appendChild(img);a.addEventListener('click',function(e){e.preventDefault();openChannel(c[0]);});grid.appendChild(a);});document.getElementById('year').textContent=new Date().getFullYear();document.documentElement.lang=currentLang;document.querySelectorAll('[data-lang]').forEach(b=>b.classList.toggle('active',b.dataset.lang===currentLang));}
async function openChannel(id){const c=channels.find(x=>String(x[0])===String(id));if(!c)return;history.replaceState(null,'','?id='+c[0]+'&lang='+currentLang);title.textContent=currentLang==='en'?c[3]:c[1];playerSection.hidden=false;grid.hidden=true;player.innerHTML='<div class="app-loading">Loading player…</div>';try{const r=await fetch(root+c[2],{credentials:'same-origin',cache:'default'});if(!r.ok)throw new Error('HTTP '+r.status);const doc=new DOMParser().parseFromString(await r.text(),'text/html');const source=doc.querySelector('.player-container iframe');if(!source||!source.src)throw new Error('player not found');const iframe=document.createElement('iframe');iframe.src=new URL(source.getAttribute('src')||source.src,location.href).href;iframe.allow=source.getAttribute('allow')||'autoplay; encrypted-media; fullscreen; picture-in-picture';iframe.allowFullscreen=true;iframe.setAttribute('referrerpolicy',source.getAttribute('referrerpolicy')||'no-referrer-when-downgrade');player.innerHTML='';player.appendChild(iframe);window.scrollTo({top:0,behavior:'smooth'});}catch(e){player.innerHTML='<div class="app-loading">Player could not be loaded.</div>';}}
function closePlayer(){playerSection.hidden=true;grid.hidden=false;player.innerHTML='';history.replaceState(null,'','?lang='+currentLang);}
document.getElementById('close-player').addEventListener('click',closePlayer);document.querySelectorAll('[data-lang]').forEach(function(b){b.addEventListener('click',function(){currentLang=b.dataset.lang;localStorage.setItem('matchpro-app-lang',currentLang);const id=new URLSearchParams(location.search).get('id');render();if(id)openChannel(id);else history.replaceState(null,'','?lang='+currentLang);});});
render();const id=new URLSearchParams(location.search).get('id');if(channels.some(x=>String(x[0])===String(id)))openChannel(id);
})();
