(function(){'use strict';
const channels=[
[7001,'Матч ТВ','matchtv.html'],[7002,'Матч Премьер','match-premier.html'],[7003,'Матч Арена','match-arena.html'],[7004,'Матч Футбол 1','match-football-1.html'],[7005,'Матч Футбол 2','match-football-2.html'],[7006,'Матч Футбол 3','match-football-3.html'],[7007,'Сетанта Спорт 1','setanta-1.html'],[7008,'Сетанта Спорт 2','setanta-2.html'],[7009,'Сетанта Украина','setanta-ua.html'],[7010,'Сетанта Спорт Плюс','setanta-plus.html'],[7011,'Евроспорт 1','eurosport-1.html'],[7012,'Евроспорт 2','eurosport-2.html'],[7013,'Окко Спорт','okko-sport.html'],[7014,'Окко Футбол','okko-football.html'],[7015,'Конный Мир','konnyj-mir.html'],[7016,'Viju Sport','viju-sport.html'],[7017,'Qazsport','qazsport.html'],[7018,'Волейбол','voleybol.html'],[7019,'Футбол','footballru.html'],[7020,'КХЛ','khl.html'],[7021,'Astrakhan Sport','astrakhan.html'],[7022,'Удар','udar.html'],[7023,'Бокс','bokstv.html'],[7024,'Боец','boyets.html'],[7025,'Fast Sports','fast-sports.html'],[7026,'NBA','nba.html'],[7027,'Беларусь 5','belarus5.html'],[7028,'Беларусь 5 Интернет','belarus5-internet.html'],[7029,'UPL 1','upl1hd.html'],[7030,'UPL 2','upl2hd.html']
];
const select=document.getElementById('channel'),player=document.getElementById('player'),status=document.getElementById('status');
channels.forEach(function(c){const o=document.createElement('option');o.value=c[0];o.textContent=c[1];select.appendChild(o)});
function showEmpty(){player.innerHTML='<div class="empty">Плеер не выбран</div>'}
async function load(id){const c=channels.find(x=>String(x[0])===String(id));if(!c)return;status.textContent='Загрузка: '+c[1];player.innerHTML='<div class="empty">Загрузка плеера…</div>';try{const r=await fetch('../'+c[2],{credentials:'same-origin',cache:'default'});if(!r.ok)throw new Error('HTTP '+r.status);const html=await r.text();const doc=new DOMParser().parseFromString(html,'text/html');const source=doc.querySelector('.player-container iframe');if(!source)throw new Error('player not found');const src=source.getAttribute('src');if(!src)throw new Error('player source not found');const iframe=document.createElement('iframe');iframe.src=new URL(src,location.origin+'/').href;iframe.allow=source.getAttribute('allow')||'autoplay; encrypted-media; fullscreen; picture-in-picture';iframe.allowFullscreen=true;iframe.setAttribute('referrerpolicy',source.getAttribute('referrerpolicy')||'no-referrer-when-downgrade');player.innerHTML='';player.appendChild(iframe);status.textContent=c[1]}catch(e){player.innerHTML='<div class="empty">Չհաջողվեց բեռնել պլեյերը</div>';status.textContent=c[1]+' — error'}}
const id=new URLSearchParams(location.search).get('id');const initial=channels.some(x=>String(x[0])===String(id))?id:String(channels[0][0]);select.value=initial;select.addEventListener('change',function(){const next=select.value;history.replaceState(null,'','?id='+encodeURIComponent(next));load(next)});load(initial);
})();
