(function(){'use strict';
const channels=Array.isArray(window.MATCHPRO_CHANNELS)?window.MATCHPRO_CHANNELS:[];
const config=window.MATCHPRO_PLAYER_CONFIG||{redirectUrl:'',oncePerDay:true,openInNewTab:true};
const params=new URLSearchParams(location.search),path=location.pathname.replace(/\/+$/,''),pathMatch=path.match(/\/([0-9]{4})(?:&lang=(ru|en))?$/i);
const requestedId=params.get('id')||(pathMatch&&pathMatch[1]);
const requestedLang=(params.get('lang')||(pathMatch&&pathMatch[2])||'').toLowerCase();
const pageFile=(location.pathname.split('/').pop()||'index.html').toLowerCase();
const origin=location.origin;
function get(k){try{return localStorage.getItem(k)}catch(_){return null}}
function set(k,v){try{localStorage.setItem(k,v)}catch(_) {}}
function detectLanguage(){if(requestedLang==='ru'||requestedLang==='en')return requestedLang;const saved=get('matchpro-language');if(saved==='ru'||saved==='en')return saved;const list=[...(navigator.languages||[]),navigator.language];for(const v of list){const c=String(v||'').toLowerCase().split(/[-_]/)[0];if(c==='ru')return'ru';if(c==='en')return'en'}return'en'}
const lang=detectLanguage();set('matchpro-language',lang);document.documentElement.lang=lang;
const channel=requestedId?channels.find(x=>String(x.id)===String(requestedId)):channels.find(x=>String(x.file).toLowerCase()===pageFile);
const tr=lang==='ru'?{intro:'Лучшие матчи — в прямом эфире',info:'Добро пожаловать в увлекательный мир спорта! У нас вы найдёте прямые трансляции самых захватывающих турниров, эксклюзивные интервью с спортсменами и аналитические обзоры от ведущих экспертов. От футбола до тенниса, от баскетбола до мотоспорта — мы освещаем всё, что любят настоящие поклонники спорта. Почувствуйте напряжение больших соревнований и следите за выступлениями любимых команд в высоком качестве. Наши спортивные платформы работают для вас 24 часа в сутки, предлагая самые свежие и яркие моменты из мира спорта. Присоединяйтесь к нам и убедитесь — спорт не знает границ!',watch:'Смотреть онлайн – ',related:'Другие спортивные каналы',copyright:'Авторские права',homeLink:'Главная',powered:'Работает на',home:'Спортивные каналы онлайн в прямом эфире'}:{intro:'The best matches — live',info:'Welcome to the exciting world of sports! Here you will find live broadcasts of the most thrilling tournaments, exclusive athlete interviews, and expert analysis. From football and tennis to basketball and motorsport, we cover what true sports fans love. Feel the excitement of major competitions and follow your favorite teams in high quality. Our sports platform is available 24 hours a day, bringing you the latest and most exciting moments from the world of sports. Join us and discover that sport knows no boundaries!',watch:'Watch online – ',related:'Other sports channels',copyright:'Copyright',homeLink:'Home',powered:'Powered by',home:'Sports channels live online'};
function meta(name,value){if(!value)return;let e=document.head.querySelector('meta[name="'+name+'"]');if(!e){e=document.createElement('meta');e.name=name;document.head.appendChild(e)}e.content=value}
function prop(name,value){if(!value)return;let e=document.head.querySelector('meta[property="'+name+'"]');if(!e){e=document.createElement('meta');e.property=name;document.head.appendChild(e)}e.content=value}
function canonical(url){let e=document.head.querySelector('link[rel="canonical"]');if(!e){e=document.createElement('link');e.rel='canonical';document.head.appendChild(e)}e.href=url}
function idUrl(id){return '/?id='+encodeURIComponent(id)+'&lang='+lang}
function seo(){const url=channel?origin+'/?id='+channel.id+'&lang='+lang:origin+'/?lang='+lang;if(channel){document.title=lang==='en'?channel.titleEn:channel.titleRu;meta('description',lang==='en'?channel.descriptionEn:channel.descriptionRu);meta('keywords',lang==='en'?channel.keywordsEn:channel.keywordsRu);prop('og:title',document.title);prop('og:description',lang==='en'?channel.descriptionEn:channel.descriptionRu);prop('og:type','website');if(channel.logo)prop('og:image',new URL(channel.logo,origin).href)}else document.title=tr.home;prop('og:url',url);canonical(url)}
function renderHome(){if(requestedId||(pageFile!=='index.html'&&pageFile!==''))return;const grid=document.querySelector('.channel-grid');if(!grid)return;grid.innerHTML='';channels.forEach(x=>{const a=document.createElement('a');a.className='channel';a.href=idUrl(x.id);const i=document.createElement('img');i.src=x.logo;i.loading='lazy';i.decoding='async';i.alt=lang==='en'?x.nameEn:x.nameRu;a.appendChild(i);grid.appendChild(a)})}
function renderRelated(){document.querySelectorAll('.related-grid').forEach(g=>{g.innerHTML='';channels.forEach(x=>{if(channel&&String(x.id)===String(channel.id))return;const a=document.createElement('a');a.className='channel';a.href=idUrl(x.id);const i=document.createElement('img');i.src=x.logo;i.loading='lazy';i.decoding='async';i.alt=lang==='en'?x.nameEn:x.nameRu;a.appendChild(i);g.appendChild(a)})})}
function text(){const intro=document.querySelector('.intro-text');if(intro)intro.textContent=tr.intro;const info=document.querySelector('.info-text');if(info)info.textContent=tr.info;const related=document.querySelector('.related-title');if(related)related.textContent=tr.related;const name=document.querySelector('.channel-name');if(name&&channel)name.innerHTML=tr.watch+'<span>'+(lang==='en'?channel.nameEn:channel.nameRu)+'</span>';const desc=document.querySelector('.channel-description');if(desc&&channel)desc.textContent=lang==='en'?channel.descriptionEn:channel.descriptionRu;document.querySelectorAll('footer').forEach(f=>{f.querySelectorAll('.matchpro-footer-links,.matchpro-powered,.matchpro-copyright').forEach(e=>e.remove());let y=f.querySelector('#year');if(y)y.textContent=new Date().getFullYear();let links=document.createElement('div');links.className='matchpro-footer-links';let home=document.createElement('a');home.href='/?lang='+lang;home.textContent=tr.homeLink;let sep=document.createElement('span');sep.textContent='•';let c=document.createElement('a');c.className='matchpro-copyright';c.textContent=tr.copyright;c.href=lang==='en'?'./copyright-en.html':'./copyright-ru.html';links.append(home,sep,c);f.appendChild(links);let p=document.createElement('p');p.className='matchpro-powered';p.innerHTML=tr.powered+' <a href="https://t.me/skyxcoding" target="_blank" rel="noopener noreferrer">SkyXCode</a>';f.appendChild(p)})}
function setupRedirect(){if(!config.redirectUrl||document.documentElement.dataset.redirectGuard)return;document.documentElement.dataset.redirectGuard='1';const key='matchpro-player-redirect:'+ (channel?channel.id:pageFile)+':'+new Date().toISOString().slice(0,10);if(config.oncePerDay&&get(key)==='1')return;const handler=function(e){const player=e.target&&e.target.closest?e.target.closest('.player-container'):null;if(player||e.defaultPrevented)return;if(config.oncePerDay)set(key,'1');document.removeEventListener('click',handler,true);document.removeEventListener('touchend',handler,true);if(config.openInNewTab)window.open(config.redirectUrl,'_blank','noopener,noreferrer');else location.href=config.redirectUrl};document.addEventListener('click',handler,true);document.addEventListener('touchend',handler,true)}
function preventCopy(){if(document.documentElement.dataset.copyGuard)return;document.documentElement.dataset.copyGuard='1';['copy','cut','paste','contextmenu','selectstart','dragstart'].forEach(e=>document.addEventListener(e,x=>x.preventDefault(),{passive:false}));document.addEventListener('keydown',e=>{if((e.ctrlKey||e.metaKey)&&['c','x','v','u','a','s','p'].includes(e.key.toLowerCase()))e.preventDefault()},{passive:false})}
function boot(){seo();renderHome();renderRelated();text();setupRedirect();preventCopy()}
window.MATCHPRO_BOOT=boot;
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot);else boot();
})();
