(function(){'use strict';
const channels=Array.isArray(window.MATCHPRO_CHANNELS)?window.MATCHPRO_CHANNELS:[];
const config=window.MATCHPRO_PLAYER_CONFIG||{redirectUrl:'',oncePerDay:true,openInNewTab:true};
const origin=window.location.origin,params=new URLSearchParams(location.search),requestedId=params.get('id'),pageFile=(location.pathname.split('/').pop()||'index.html').toLowerCase();
function storageGet(k){try{return localStorage.getItem(k)}catch(_){return null}}function storageSet(k,v){try{localStorage.setItem(k,v)}catch(_){}
}
function detectLanguage(){const p=params.get('lang');if(p==='ru'||p==='en')return p;const saved=storageGet('matchpro-language');if(saved==='ru'||saved==='en')return saved;const list=[...(navigator.languages||[]),navigator.language];for(const v of list){const c=String(v||'').toLowerCase().split('-')[0].split('_')[0];if(c==='ru')return'ru';if(c==='en')return'en'}return'en'}
const lang=detectLanguage();storageSet('matchpro-language',lang);document.documentElement.lang=lang;
const channel=requestedId?channels.find(x=>String(x.id)===String(requestedId)):channels.find(x=>String(x.file).toLowerCase()===pageFile);
const tr=lang==='ru'?{intro:'Лучшие матчи — в прямом эфире',share:'Поделиться',copied:'Скопировано',watch:'Смотреть онлайн – ',related:'Другие спортивные каналы',copyright:'Авторские права',home:'Спортивные каналы онлайн в прямом эфире'}:{intro:'The best matches — live',share:'Share',copied:'Copied',watch:'Watch online – ',related:'Other sports channels',copyright:'Copyright',home:'Sports channels live online'};
function ensureMeta(n,c){if(!c)return;let e=document.head.querySelector('meta[name="'+n+'"]');if(!e){e=document.createElement('meta');e.name=n;document.head.appendChild(e)}e.content=c}function ensureProp(n,c){if(!c)return;let e=document.head.querySelector('meta[property="'+n+'"]');if(!e){e=document.createElement('meta');e.property=n;document.head.appendChild(e)}e.content=c}function canonical(u){let e=document.head.querySelector('link[rel="canonical"]');if(!e){e=document.createElement('link');e.rel='canonical';document.head.appendChild(e)}e.href=u}
function seo(){if(channel){document.title=lang==='en'?channel.titleEn:channel.titleRu;ensureMeta('description',lang==='en'?channel.descriptionEn:channel.descriptionRu);ensureMeta('keywords',lang==='en'?channel.keywordsEn:channel.keywordsRu);ensureProp('og:title',document.title);ensureProp('og:description',lang==='en'?channel.descriptionEn:channel.descriptionRu);ensureProp('og:type','website');if(channel.logo)ensureProp('og:image',new URL(channel.logo,origin).href);ensureProp('og:url',origin+'/?id='+channel.id);canonical(origin+'/?id='+channel.id)}else{document.title=tr.home;canonical(origin+'/')} }
function renderHomepage(){if(requestedId||(pageFile!=='index.html'&&pageFile!==''))return;const grid=document.querySelector('.channel-grid');if(!grid)return;grid.innerHTML='';channels.forEach(x=>{const a=document.createElement('a');a.className='channel';a.href='./?id='+x.id+'&lang='+lang;const i=document.createElement('img');i.src=x.logo;i.loading='lazy';i.decoding='async';i.alt=lang==='en'?x.nameEn:x.nameRu;a.appendChild(i);grid.appendChild(a)})}
function renderRelated(){document.querySelectorAll('.related-grid').forEach(g=>{g.innerHTML='';channels.forEach(x=>{if(channel&&String(x.id)===String(channel.id))return;const a=document.createElement('a');a.className='channel';a.href='./?id='+x.id+'&lang='+lang;const i=document.createElement('img');i.src=x.logo;i.loading='lazy';i.decoding='async';i.alt=lang==='en'?x.nameEn:x.nameRu;a.appendChild(i);g.appendChild(a)})})}
function languageSwitch(){if(document.querySelector('.matchpro-language-switcher'))return;const h=document.querySelector('header');if(!h)return;const b=document.createElement('div');b.className='matchpro-language-switcher matchpro-language';b.setAttribute('aria-label','Language');b.innerHTML='<button type="button" data-lang="ru">RU</button><button type="button" data-lang="en">EN</button>';b.querySelectorAll('button').forEach(x=>{if(x.dataset.lang===lang)x.classList.add('active');x.addEventListener('click',()=>{storageSet('matchpro-language',x.dataset.lang);const u=new URL(location.href);u.searchParams.set('lang',x.dataset.lang);location.href=u.toString()})});h.appendChild(b)}
function text(){const intro=document.querySelector('.intro-text');if(intro)intro.textContent=tr.intro;const name=document.querySelector('.channel-name');if(name&&channel)name.innerHTML=tr.watch+'<span>'+(lang==='en'?channel.nameEn:channel.nameRu)+'</span>';const desc=document.querySelector('.channel-description');if(desc&&channel)desc.textContent=lang==='en'?channel.descriptionEn:channel.descriptionRu;const share=document.querySelector('.share-button');if(share&&!share.dataset.bound){share.dataset.bound='1';share.addEventListener('click',async()=>{try{await navigator.clipboard.writeText(location.href)}catch(_){}share.textContent='✓ '+tr.copied;setTimeout(()=>{share.textContent='↗ '+tr.share},1500)})}document.querySelectorAll('footer').forEach(f=>{f.querySelectorAll('.matchpro-powered,.matchpro-copyright').forEach(e=>e.remove());const c=document.createElement('a');c.className='matchpro-copyright';c.textContent=tr.copyright;c.href=lang==='en'?'./copyright-en.html?lang=en':'./copyright-ru.html?lang=ru';f.appendChild(c);const p=document.createElement('p');p.className='matchpro-powered';p.innerHTML='Powered by <a href="https://t.me/skyxcoding" target="_blank" rel="noopener noreferrer">SkyXCode</a>';f.appendChild(p);const y=f.querySelector('#year');if(y)y.textContent=new Date().getFullYear()})}
function playerGate(){const iframe=document.querySelector('.player-container iframe');if(!iframe||!config.redirectUrl||iframe.dataset.gate)return;iframe.dataset.gate='1';const p=iframe.parentElement;p.style.position=p.style.position||'relative';const o=document.createElement('button');o.type='button';o.setAttribute('aria-label',lang==='en'?'Open player':'Открыть плеер');o.style.cssText='position:absolute;inset:0;width:100%;height:100%;padding:0;border:0;background:transparent;cursor:pointer;z-index:20';p.appendChild(o);const key='matchpro-player-redirect:'+(channel?channel.id:pageFile)+':'+new Date().toISOString().slice(0,10);if(config.oncePerDay&&storageGet(key)==='1')o.style.pointerEvents='none';o.addEventListener('click',()=>{if(config.oncePerDay&&storageGet(key)==='1'){o.style.pointerEvents='none';return}if(config.oncePerDay)storageSet(key,'1');o.style.pointerEvents='none';if(config.openInNewTab)window.open(config.redirectUrl,'_blank','noopener,noreferrer');else location.href=config.redirectUrl})}
function preventCopy(){['copy','cut','paste','contextmenu','selectstart','dragstart'].forEach(e=>document.addEventListener(e,x=>x.preventDefault(),{passive:false}));document.addEventListener('keydown',e=>{if((e.ctrlKey||e.metaKey)&&['c','x','v','u','a','s','p'].includes(e.key.toLowerCase()))e.preventDefault()},{passive:false})}
function boot(){seo();renderHomepage();renderRelated();languageSwitch();text();playerGate();preventCopy()}if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot);else boot();
})();
