import fs from 'node:fs';
import path from 'node:path';
const ROOT=process.cwd(),errors=[],warnings=[];
const exists=p=>fs.existsSync(path.join(ROOT,p));
const read=p=>fs.readFileSync(path.join(ROOT,p),'utf8');
function files(dir=ROOT){const out=[];for(const e of fs.readdirSync(dir,{withFileTypes:true})){if(['.git','node_modules'].includes(e.name))continue;const f=path.join(dir,e.name);if(e.isDirectory())out.push(...files(f));else out.push(path.relative(ROOT,f).replaceAll(path.sep,'/'));}return out;}
const allFiles=files(),htmlFiles=allFiles.filter(f=>f.toLowerCase().endsWith('.html')),rootHtml=htmlFiles.filter(f=>!f.includes('/')),iframeHtml=htmlFiles.filter(f=>f.startsWith('iframe/'));
function localTarget(raw,source){if(!raw)return null;const v=raw.trim().replace(/^['"]|['"]$/g,'');if(!v||v.startsWith('#')||v.startsWith('//')||/^(?:https?:|data:|mailto:|tel:|javascript:|blob:)/i.test(v))return null;const clean=v.split('#')[0].split('?')[0];if(!clean)return null;if(clean.startsWith('/'))return clean.slice(1);return path.posix.normalize(path.posix.join(path.posix.dirname(source),clean)).replace(/^\.\//,'');}
function checkLocalRefs(file,content){const re=/\b(?:src|href|poster|action)\s*=\s*["']([^"']+)["']/gi;for(const m of content.matchAll(re)){const target=localTarget(m[1],file);if(target&&!exists(target))errors.push(`${file}: missing local resource ${m[1]} -> ${target}`);}}
function validateDocument(file,fullPage){const c=read(file);if(fullPage&&!/^\s*<!doctype html>/i.test(c))errors.push(`${file}: missing HTML5 doctype`);if(!/<html\b/i.test(c))errors.push(`${file}: missing html element`);if(!/<meta\b[^>]*charset\s*=\s*["']?utf-8/i.test(c))errors.push(`${file}: missing UTF-8 charset`);if(fullPage){if(!/<html\b[^>]*\blang\s*=\s*["'][^"']+["']/i.test(c))errors.push(`${file}: missing html lang`);if(!/<meta\b[^>]*name\s*=\s*["']viewport["']/i.test(c))errors.push(`${file}: missing viewport meta`);if(!/<title\b[^>]*>[^<]+<\/title>/i.test(c))errors.push(`${file}: missing meaningful title`);if(!['index.html','404.html','403.html','500.html'].includes(file)&&(c.match(/<main\b/gi)||[]).length!==1)errors.push(`${file}: expected exactly one <main>`);if((c.match(/<header\b/gi)||[]).length>1)errors.push(`${file}: duplicate <header>`);if((c.match(/<footer\b/gi)||[]).length>1)errors.push(`${file}: duplicate <footer>`);}if(!/<\/html>\s*$/i.test(c))errors.push(`${file}: malformed document ending`);checkLocalRefs(file,c);for(const m of c.matchAll(/<iframe\b[^>]*\bsrc\s*=\s*["']([^"']+)["']/gi)){const target=localTarget(m[1],file);if(target&&!exists(target))errors.push(`${file}: iframe target missing ${m[1]}`);}}
for(const f of rootHtml)validateDocument(f,true);for(const f of iframeHtml)validateDocument(f,false);
const channelsFile='main/js/channels.js';
if(!exists(channelsFile))errors.push('main/js/channels.js: file missing');else{const c=read(channelsFile),entries=[...c.matchAll(/\{\s*id\s*:\s*(\d+)\s*,\s*file\s*:\s*['"]([^'"]+)['"]/g)].map(m=>({id:m[1],file:m[2]}));if(entries.length!==30)errors.push(`channels.js: expected 30 registered channels, found ${entries.length}`);const ids=new Set(),mapped=new Set();for(const x of entries){if(ids.has(x.id))errors.push(`channels.js: duplicate channel id ${x.id}`);if(mapped.has(x.file))errors.push(`channels.js: duplicate channel file ${x.file}`);ids.add(x.id);mapped.add(x.file);if(!exists(x.file))errors.push(`channels.js: registered page missing ${x.file}`);}const allowed=new Set(['index.html','404.html','403.html','500.html','copyright-en.html','copyright-ru.html',...entries.map(x=>x.file)]);for(const f of rootHtml)if(!allowed.has(f))warnings.push(`orphan root HTML not registered as a channel: ${f}`);}
if(warnings.length)for(const w of warnings)console.log(`::warning::${w}`);
if(errors.length){console.error(`Integrity check failed: ${errors.length} error(s)`);for(const e of errors)console.error(`::error::${e}`);process.exit(1);}console.log(`MatchPro integrity check passed: ${rootHtml.length} root HTML + ${iframeHtml.length} iframe HTML files checked; 30 channel mappings verified.`);
